export default {
  myApp: "My App",
  _myApp: "Software",
  Y: "Run",
  Renew: "Renew",
  install: "Install",
  emulator: "Emulator",
  platform: "Platform",
  empty: "Your app is empty.",
  uninstall: "uninstall",
  development: "Development",
  system: "System",
  other: "Other",
  apperror: "Software startup failed",
  updateError: "Update failed",
  installError: "Installation failed",
  noApp: "No app found",
  nowifi: "No app found, try again",
};
