export default {
  title: "Assistant",
  fast: "Fast",
  file: "File",
  community: "Community",
  gallery: "Gallery",
  closed: "Closed",
  activated: "Activated",
  upadte: "Upadte",
  hasUpdate: "Can be updated",
  pc: "Explore the possibilities of PC handhelds",
  emulator_: "Emulator",
  setUp: "Set Up",
  master1: "Master Controller",
  master2: "Unparalleled Sense of Control",
  master3: "Configure your operating mode",
  emulator: {
    global: "Global",
    Independent: "Independent",
    expand: "Expand",
    shrink: "Shrink",
    advanced: "Advanced",
    emulator_core: "Emulator Core",
    ratio: "Ratio",
    videomodel: "Video Model",
    shaderset: "Shaderset",
    bezel: "Bezel",
    gfxbackend: "Graphics API",
    refreshGame: "Game list refresh",
    refresNow: "Refresh Now",
    refreshSuccess: "Refresh succeeded",
    refreshFailed: "Refresh failed",
  },
  GameGallery: {
    sync: "Auto Sync",
    null: "Your Game Gallery is empty",
    openList: "Open List",
  },
  EjectImg: {
    loading: "uploading...",
    error: "Upload failed",
    Retry: "Retry",
    qrcode1: "Scan the QR code",
    qrcode2: "View game screenshots",
    del: "successfully deleted",
  },
  Message: {
    title: "Instructions and reminders",
    text1:
      "You are preparing to enable the automatic screenshot upload function, which provides a better experience for you to share game screenshots. At the same time, the uploaded screenshot data will be saved in your personal database on the AYANEO server. The use of data and synchronization functions requires your consent. Please read carefully",
    agreement: "《Software License Agreement》",
    privacy: "《Privacy Policy》",
    text2:
      ", turning on this feature will mean that you understand and understand our relevant policies.",
    true: "I understand, turn this feature on",
    false: "Do not accept",
    and: "And",
  },
  AYAlink: {
    title: "WiFi Transfer",
    nowWifi: "current network:",
    hink: "Please use a browser under the same network to access",
    off_: "Service is down",
    wait: "Service is on",
    on: "ON",
    off: "OFF",
    password: "The initial account password is: ayaneo",
  },
};
