export default {
  home: "Home",
  game: "Installed Games",
  retroGame: "Retro Games",
  apps: "Software",
  assostant: "Assistant",
  gallery: "Game Gallery",
  Avatar: {
    appreciate: "appreciate",
    login: "Login",
    noLogin: "Not Logged In",
    dataSync: "Data Sync",
    new: "New",
    conente: "Update Content",
    logoOut: "Sign out",
    old: "Previous Version",
    power: "Power",
  },
  shutdownNemu: {
    secondConfirm: "shut down?",
    minimize: "Minimize",
    exit: "Exit",
    sleep: "Hibernate",
    reboot: "Restart",
    shutdown: "Power Off",
  },
  closeWindow: "Confirm to exit AYASpace?",
  tips: {
    notice: "Notice",
    set: "Settings",
    shutdown: "Shutdown menu",
  },
  drawer: {
    qa: "FAQ",
    GameManage: "Game Management",
  },
  newFeatures: {
    title: "New Features of AYASpace 2.0",
    content: "Update content",
  },
};
