export default {
  myApp: "Mon App",
  _myApp: "Logiciel",
  Y: "Exécuter",
  Renew: "Renouveler",
  install: "Installer",
  emulator: "Émulateur",
  platform: "Plateforme",
  empty: "Votre app est vide.",
  uninstall: "Désinstaller",
  development: "Développement",
  system: "Système",
  other: "Autre",
  apperror: "Échec du démarrage du logiciel",
  updateError: "Échec de la mise à jour",
  installError: "Échec de l'installation",
  noApp: "Aucune app trouvée",
  nowifi: "Aucune app trouvée, réessayez",
};
