export default {
  sort: "Trier",
  run: "Lancer",
  flod: "Fermer",
  empty: "Vide",
  openSteam: "Ouvrir Steam",
  manage: "Gérer",
  gameIsRunning: "Le jeu est déjà en cours d'exécution",
  Confirm: "Confirmer",
  QFind: {
    pc: "Jeux installés",
    initials: "Initiales",
    label: "Étiquette",
    platform: "Plateforme",
    type: "Type",
    publish: "Éditeur",
    manufacturer: "Fabricant",
    removeAll: "tout supprimer",
    selected: "sélectionné",
    item: "",
    common: "Total",
  },
  SortPopups: {
    layout: "Disposition",
    largeGrid: "Mode Grille",
    DetailsList: "Mode Liste",
    columns: "Colonnes",
    sort: "Trier",
    Playtime: "Par Temps de Jeu",
    StorageTime: "Par Date d'Ajout",
    gameName: "Par Nom",
    Ascending: "Ordre Ascendant",
    Descending: "Ordre Descendant",
    buttonX: "Application",
  },
  GameDefault: {
    noGame: "Aucun jeu pour le moment",
    steam: "Installation et importation de jeux Steam",
    other: "Installation et importation d'autres jeux PC",
    retro: "Importation de jeux rétro",
    select: "sélectionner",
    supportSystem: "Système de support",
    GameTransferProcess: "Transfert de jeu",
    Disclaimer: "Clause de non-responsabilité",
    nostalgia:
      "La bibliothèque nostalgique d'AYANEO OS est seulement un outil de gestion de contenu et ne fournit pas de Roms et de BIOS.",
    privateGame:
      "Le jeu privé importé par vous dans la bibliothèque nostalgique d'AYANEO OS, assurez-vous d'avoir le droit d'utiliser le jeu, et les droits d'auteur du jeu appartiennent à l'éditeur du jeu et à l'équipe de production du jeu",
    gameModification:
      "AYANEO OS ne assume aucune responsabilité pour les conséquences des opérations des joueurs telles que la modification et la suppression de jeux",
    coming: "bientôt disponible",
  },
  GameDetails: {
    from: "De",
    installed: "Installé",
    gameTime: "Temps de jeu",
    h: "h",
    data: "Options",
    playGame: "Lancer",
    settings: "Émulateur",
    video: "Vidéo",
    hour: "Heure(s)",
    Art: "Mur artistique",
    Cutover: "Changement",
    Full: "Plein écran",
    outFull: "Quitter le plein écran",
    Play: "Lire",
    Stop: "Arrêter",
    noVideo: "Temporairement pas de vidéo",
    noWall: "Temporairement pas de données d'art mural",
  },
  GameManage: {
    currentData: "Données de jeu actuelles",
    hide: "cacher",
    Hidden: "Caché",
    data: "Données",
    search: "Recherche manuelle",
    remove: "Supprimer l'enregistrement",
    uninstall: "Désinstaller le jeu",
    noFound: "Aucun résultat correspondant trouvé.",
    search1: "total",
    search2: "données de jeu trouvées",
    hideGame: "cacher ce jeu",
    uninstallGame: "Voulez-vous désinstaller ce jeu",
    removeGame: "Voulez-vous supprimer les jeux et les enregistrements",
    SecondConfirmation: "Utiliser cette donnée comme information d'affichage de jeu ?",
    isSuccess: "Succès",
    isError: "Erreur",
    mod: "Modification de données",
    // espace
    cloudData: "Données Cloud",
    deleteGame: "Supprimer le jeu",
    removeLibrary: "Supprimer de la bibliothèque",
    del: "Jeu supprimé",
    failed: "Échec de la suppression du jeu",
    removed: "Jeu supprimé",
    Whether: "Voulez-vous utiliser cette donnée comme information d'affichage de jeu ?",
    toHide: "Voulez-vous masquer ce jeu",
    toShow: "Voulez-vous afficher ce jeu",
    deleted: "Supprimé avec succès",
    fled: "Échec de la suppression",
  },
  // espace Gestion des jeux selon le nom du fichier
  management: {
    title: "Gestion des jeux",

    firstName: {
      addGame: "Ajouter des jeux",
    },
    lastName: {
      uninstall: "Désinstaller le jeu",
      unknownFile: "Fichiers de jeu potentiels",
    },
    manageIndex: {
      title1: "Gérez votre collection de jeux privée",
      title2: "Profitez d'un contrôle sans précédent",
      addGame: "Ajouter un jeu",
      games: "Jeux",
      uninstall: "Désinstaller le jeu",
      suspectedGame: "Fichiers de jeu potentiels",
      none: "Aucun",
      unknowFile: "Gestion des jeux inconnus",
      Manual: "Ajout manuel",
      Hidden: "Éléments cachés",
      hide: "Caché",
    },
    winAddGame: {
      newGame: "Nouveau jeu",
      scanGame: "Scanner les jeux",
    },
    winDelGame: {
      select1: "Sélectionnez les jeux que vous souhaitez ",
      uninstall: "désinstaller",
      select2: "",
      mark: "Sélectionner",
      press: "Appuyez longuement pour désinstaller",
      total: "Total sélectionné",
      games: "Jeux",
      Uninstall: "Voulez-vous désinstaller le jeu sélectionné ?",
    },
    winHandAdd: {
      isGameFile: "Lesquels des éléments suivants sont des fichiers de jeu ?",
      tryLaunch: "Essayer de lancer",
      // games: "jeux",
      // file: "Fichier ?",
      FileLocation: "Emplacement du fichier :",
      TextMessage4: "Le fichier sélectionné est déjà",
      added: "ajouté",
      library: "Accédez à la bibliothèque de jeux",
      longPress: "Appuyez longuement pour exclure",
      launch: "Essayer de lancer",
      select: "Veuillez sélectionner le fichier de lancement du jeu",
      common: "Répertoire commun",
      add: "Ajouter un répertoire",
      remove: "Supprimer un répertoire",
      Scanning: "Balayage en cours...",
      Rescan: "Nouveau balayage",
      Scan: "Échec du balayage",
      AddGame: "Balayage terminé, Ajout d'un nouveau jeu :",
      current: "Enregistrez le répertoire actuel",
      Previous: "Répertoire précédent",
      Enter: "Entrer dans le répertoire",
      Close: "Fermer la case à cocher",
      Back: "Revenir en arrière",
      whether: "voulez-vous supprimer le répertoire",
      Installed: "Il n'y a aucun jeu installé",
      try: "Utilisez la",
      management: "gestion des jeux",
      designed: "fonctionnalité pour ajouter des jeux.",
      Start: "pour lancer la gestion des jeux",
      Added: "Ajouté aux jeux installés",
    },
    data: {
      Management: "Gestion des données",
      Modification: "Modification des données",
      name: "Nom du jeu",
      Describe: "Description",
      label: "Étiquette du jeu",
      add: "Ajouter une étiquette",
      logo: "LOGO du jeu",
      cover: "Couverture du jeu",
      back: "Fond du jeu",
      save: "Enregistrer",
      cancellation: "Annulation",
      Uploading: "Téléchargement",
      Notice: "Avis",
      noNotice: "Aucun avis temporaire.",
      modified: "Modifié avec succès",
      All: "Lire tout",
      Clear: "Effacer l'enregistrement",
    },
    home: {
      run: "Jeu en cours d'exécution",
      enjoy: "Profitez de votre jeu",
      Close: "Fermer",
      exit: "Quitter le jeu",
      continue: "Continuer le jeu",
      Expand: "Étendre",
      Running: "En cours d'exécution",
      s: "s",
      failed: "Échec du démarrage du jeu, veuillez vérifier le lanceur de jeu",
      an: "Appuyez sur",
      open: "pour ouvrir le lanceur",
      game: "Fermer le jeu",
      start: "Préparation pour démarrer",
      wait: "Attendre",
    }
  },
};
