export default {
  add: "Ajouter",
  cancel: "Annuler",
  close: "Fermer",
  confirm: "Confirmer",
  crossKey: "Sélectionner",
  del: "Supprimer",
  press: "Appuyer",
  return: "Retour",
  remove: "Retirer",
  share: "Partager",
  toggle: "Basculer",
  more: "Plus",
  saveAndApply: "Enregistrer et Appliquer",
};
