export default {
  title: "Assistant",
  fast: "Rapide",
  file: "Fichier",
  community: "Communauté",
  gallery: "Galerie",
  closed: "Fermé",
  activated: "Activé",
  upadte: "Mise à jour",
  hasUpdate: "Peut être mis à jour",
  pc: "Explorez les possibilités des ordinateurs portables",
  emulator_: "Émulateur",
  setUp: "Configurer",
  master1: "Contrôleur principal",
  master2: "Sens de contrôle inégalé",
  master3: "Configurez votre mode d'exploitation",
  emulator: {
    global: "Global",
    Independent: "Indépendant",
    expand: "Étendre",
    shrink: "Réduire",
    advanced: "Avancé",
    emulator_core: "Noyau de l'émulateur",
    ratio: "Ratio",
    videomodel: "Modèle vidéo",
    shaderset: "Ensemble de shaders",
    bezel: "Bordure",
    gfxbackend: "API graphique",
    refreshGame: "Actualiser la liste des jeux",
    refresNow: "Actualiser maintenant",
    refreshSuccess: "Actualisation réussie",
    refreshFailed: "Échec de l'actualisation",
  },
  GameGallery: {
    sync: "Synchronisation automatique",
    null: "Votre galerie de jeux est vide",
    openList: "Ouvrir la liste",
  },
  EjectImg: {
    loading: "Chargement en cours...",
    error: "Échec du téléchargement",
    Retry: "Réessayer",
    qrcode1: "Scannez le code QR",
    qrcode2: "Affichez les captures d'écran du jeu",
    del: "Supprimé avec succès",
  },
  Message: {
    title: "Instructions et rappels",
    text1:
      "Vous vous apprêtez à activer la fonction de téléchargement automatique de captures d'écran, qui offre une meilleure expérience pour partager les captures d'écran du jeu. En même temps, les données des captures d'écran téléchargées seront enregistrées dans votre base de données personnelle sur le serveur AYANEO. L'utilisation des données et des fonctions de synchronisation nécessite votre consentement. Veuillez lire attentivement",
    agreement: "《Contrat de licence logicielle》",
    privacy: "《Politique de confidentialité》",
    text2:
      ", activer cette fonction signifiera que vous comprenez et acceptez nos politiques pertinentes.",
    true: "Je comprends, activez cette fonction",
    false: "Je n'accepte pas",
    and: "Et",
  },
  AYAlink: {
    title: "Transfert WiFi",
    nowWifi: "Réseau actuel :",
    hink: "Veuillez utiliser un navigateur sous le même réseau pour accéder",
    off_: "Le service est hors ligne",
    wait: "Le service est en marche",
    on: "ACTIVÉ",
    off: "DÉSACTIVÉ",
    password: "Le mot de passe initial du compte est : ayaneo",
  },
};
