export default {
  thanks: "Merci d'avoir choisi",
  selsectLang: "Langue",
  next: "Étape suivante",
  enjoy: "Veuillez profiter du jeu",
  selectWifi: "Wifi",
  WiFiClose: "Le WiFi est désactivé",
  WiFiAdapter: "Impossible de trouver le WiFi",
  WiFiNetwork: "Aucun réseau",
  Y: "Passer",
  R: "Faire défiler",
  UserAgreement: "Politique de confidentialité",
  agree: "Accepter et continuer",
  goEnjoy: "Profitez de votre vie de joueur",
  goPlay: "pour jouer",
};
