export default {
  model: "modèle",
  total: "Temps de jeu : ",
  power: "mode d'alimentation ",
  temperature: "℃",
  wifiNoConnected: "Wifi non connecté",
  openWifi: "Activer le wifi",
  bluetooth: "Bluetooth",
  gameMode: "Jeu",
  balanced: "Équilibré",
  saving: "Économie",
  home: "Accueil",
  PCGames: "Jeux installés",
  hour: "Heure(s)",
  Select: "Sélectionner",
  Confirm: "Confirmer",
  default: {
    welcome: "Bienvenue",
    p1: "Aucun jeu pour le moment, veuillez vous connecter à Steam pour télécharger vos jeux",
    p2: "Ou importez d'autres jeux",
    startUp: "Démarrer",
    howRetro: "Comment importer des jeux rétro",
  },
  second: {
    fracticon: "Les hautes notes joueront",
    noPlay: "Les hautes notes doivent jouer",
    noWifi1: "Veuillez vous connecter à Internet pour obtenir les données du jeu. Appuyez sur",
    noWifi2: "Ouvrir les paramètres réseau",
  },
};
