export default {
  performance: {
    Performance: "Performance",
    Lock: "Limitation FPS",
    Trimmer: "Limitation TDP",
    Float: "Surimpression de performance",
    style: "Format",
    Simple: "Simple",
    custom: "Personnalisé",
    fan: "Configuration du ventilateur",
    software: "Contrôle logiciel",
    hardeare: "Contrôle matériel",
    Unlimited: "Illimité",
    Config: "Configuration RPM",
    Mode: "Mode échelle",
    Mode1: "Mode RPM",
    Mode2: "Mode linéaire",
    Mute: "Muet",
    Balanced: "Équilibré",
    max: "Max",
    Custom: "Personnalisé",
    qsw: "100%",
    FPSsome: "Dans certains cas, limiter le taux de trame cible peut stabiliser les FPS, mais il est recommandé de ne pas le limiter. Cette fonction invoque le pilote AMD, et cette fonction sera invalide lors de l'utilisation de RSR.",
    TDPQuickly: "Ajustez rapidement le TDP pour vous aider à obtenir une meilleure expérience dans les jeux que vous exécutez.",
    Exclusive: "Il est recommandé d'utiliser FPSThunder pour une excellente expérience. Vous devez installer les bibliothèques dépendantes lors de la première utilisation, veuillez les installer/réparer selon les invites.",
    dissatisfied: "Si vous n'êtes pas satisfait du bruit de la machine en cours d'exécution, vous pouvez ajuster de manière flexible la stratégie du ventilateur selon votre situation personnelle.",
  },
  controller: {
    Controller: "Contrôleur",
    Vibration: "Vibration",
    custom: "Personnalisé",
    Low: "Faible",
    Middle: "Moyen",
    High: "Élevé",
    Close: "Désactivé",
    violent: "violent",
    soft: "doux",
    Trigger: "Déclencheur analogique",
    Sensitivity: "Sensibilité",
    Joystick: "Joystick",
    mode: "Ajustement de la plage",
    Custom: "Personnalisé",
    model: "Mode ABXY",
    Normal: "Normal",
    Japanese: "Japonais",
    fully: "Entièrement automatique",
    semi: "Semi-automatique",
    Non: "Non récurrent",
    Gyro: "Gyro",
    adjus: "Ajustement du Gyro",
    StartKey: "Touche rapide",
    RGB: "Mode RGB",
    Switch: "Activer",
    Mode1: "Mode",
    Brightness: "Luminosité",
    Automatic: "Auto",
    Gamepad: "Désactiver le contrôleur",
    Reset: "Réinitialiser",
    Default: "Par défaut",
    breath: "Respiration monochrome",
    loop: "Respiration RGB",
    goole: "Respiration Google",
    Scanning: "Radar",
    Repple: "Ripple",
    always: "Toujours monochrome",
    LeftJoy: "Joystick gauche",
    RightJoy: "Joystick droit",
    XBOX: "Touches standard XBox",
    swap: "Échange des touches AB / XY, disposition SNES",
    sensitivity: "Réglez la sensibilité que vous souhaitez pour les deux touches de déclenchement, il vous offrira une expérience de fonctionnement fluide",
    joysticks: "Réglez la sensibilité que vous souhaitez pour les deux joysticks, cela sera plus conforme à vos habitudes de fonctionnement",
    down: "Maintenez le bouton enfoncé, Rafale de 20 fois/s",
    Click: "Cliquez une fois, Rafale automatique, Appuyez de nouveau pour arrêter ;"
  },
  psp: {
    Handheld: "Options de console portable",
    Brightness: "Luminosité",
    Volume: "Volume",
    mode: "Mode avion",
    Bluetooth: "Bluetooth",
    WIFI: "Wi-Fi",
    Mute: "Muet",
    screen: "Télécharger avec l'écran éteint",
  },
  quickSetup: {
    quick: "Assistant rapide",
    quicktool: "Gestion des paramètres rapides",
    win: "Win",
    game: "Fermer le jeu",
    osk: "OSK",
    Mute: "Muet",
    Hibernate: "Mise en veille",
    WIFI: "Wi-Fi",
    Bluetooth: "Bluetooth",
    USB: "Contrôleur USB",
    full: "Plein écran",
    Minimize: "Réduire",
    mouse: "Mode joystick",
    Optional: "Optionnel",
    Screenshot: "Capture d'écran",
    Vibration: "Vibration",
    mode: "Mode avion",
    Reset: "Réinitialiser",
    Done: "Accepter",
    Remove: "Supprimer",
    Gamepad: "Désactiver le contrôleur",
    multitasking: "Multitâche",
    GameOverlay: "Surimpression de jeu",
    increase: "Ajouter plus",
    Undefined: "Non défini",
    Mouse: "Souris simulée",
    ESC: "ESC",
    FSR: "FSR",
  },
  settings: {
    System: "Système",
    aya: "AYANEO Handheld",
    check: "Vérifier les mises à jour",
    Systems: "Paramètres du système",
    FAQ: "FAQ",
    windows: "Options Windows",
    task: "Gestionnaire des tâches",
    device: "Gestionnaire de périphériques",
    control: "Panneau de configuration",
    file: "Gestionnaire de fichiers",
    set: "Paramètres Windows",
    display: "Paramètres Windows",
    Update: "Aucune mise à jour",
    Immediately: "Immédiatement",
  }
};
