export default {
  center: {
    quickSet: "Configuration rapide",
    power: "Puissance actuelle",
    handle: "",
    tool: "Outil d'émulateur",
    menu: "Menu",
    filter: "Basculer le filtre",
    rebot1: "Redémarrer",
    rebot2: "Jeu",
    rebot3: "Logiciel",
    add: "Ajouter un widget",
    fan: "Ventilateur",
    auto: "Auto",
    simple: "Simple",
    ordinary: "Ordinaire",
    A_: "Supprimé",
    screenshotSucces: "La capture d'écran a réussi",
  },
  component: {
    management: "Gestion des contrôles",
    optional: "Optionnel",
    quickControl: "Contrôle rapide",
    added: "Ajouté",
    gyro: "Gyro",
    sensitivity: "Sensibilité",
    startKey: "Touche de démarrage",
    press: "Appuyer",
    gyroAiming: "Démarrage automatique du ciblage gyroscopique",
    windowManagement: "Gestion du contrôle du widget",
    archive: "Archiver",
    middle: "Moyen",
    low: "Faible",
    high: "Élevé",
  },
};
