export default {
  connect: "Connecter",
  connected: "Connecté",
  disconnect: "Déconnecter",
  noconnect: "Non connecté",
  open: "Ouvrir",
  self: {
    title: "Assistant",
    setUp: "Configuration",
    account: "Compte",
    bluetooth: "Bluetooth",
    themeSettings: "Thème",
    language: "Langue",
    timeZone: "Fuseau horaire",
    server: "Serveur",
    aboutDevice: "Infos sur l'appareil",
    library: "Bibliothèques tierces",
    renew: "Renouveler",
    Activated: "Activé",
    Unopened: "Non ouvert",
    noRenew: "Pas de mise à jour",
    hasRenew: "Mises à jour",
  },
  aboutDevice: {
    text: "Nom de l'appareil",
    version: "Version",
    storage: "Stockage",
    available: "Disponible",
    all: "Total",
    model: "Modèle de l'appareil",
    serial: "Numéro de série",
    software: "Version du logiciel",
  },
  ThemeSettings: {
    settingsTheme: "Paramètres du thème",
    playVideo: "Lire la vidéo",
    videoMusic: "Musique de la vidéo",
    system: "Système",
    soundEffect: "Effet sonore",
    backgroundMusic: "Musique de fond",
  },
  AboutAccount: {
    title: "Sécurité du compte",
    name: "Pseudo",
    avatar: "Avatar",
    phone: "Numéro de téléphone",
    message: "Paramètres des informations personnelles, recommandé",
    noLogin: "Non connecté",
    signOut: "Se déconnecter",
    login: "Se connecter",
    isSure: "Confirmer la déconnexion?",
  },
  FormatTF: {
    title: "Formater la carte TF",
    operate: "Confirmer le formatage de la carte TF",
    warning: "Veuillez procéder avec prudence.",
    success: "Carte TF formatée",
  },
  SecondConfirmation: {
    Whether: "Confirmer",
  },
  reset: {
    title: "Réinitialiser les paramètres d'usine",
    data: "Conserver les données de jeu et restaurer les paramètres du système",
    noData: "Effacer toutes les données locales et restaurer les paramètres du système",
  },
  timer: {
    timerTitle: "Heure",
    Automatic: "Auto",
    date: "Date",
    year: "Année",
    month: "Mois",
    day: "Jour",
    timeFormat: "Format de l'heure",
    HourSystem: "Système horaire",
    confirm: "Confirmer",
    timeZone: "Fuseau horaire",
    twenty: "Format 24 heures",
    twelve: "Format 12 heures",
    am: "AM",
    pm: "PM",
    AutoSuccess: "Obtenu automatiquement",
  },
  servers: {
    serversTitle: "Serveur de connexion",
    zh: "Serveur chinois",
    en: "Serveur international",
    msg: "Vous devez vous reconnecter après avoir changé de serveur",
  },
  wifi: {
    wifiTitle: "Réseau",
    nowWifi: "Réseau actuel :",
    off_: "Déconnecté",
    password: "Mot de passe",
    input: "",
    wifiPassword: "",
    error: "Mot de passe incorrect, veuillez réessayer",
    HoldOn: "Patientez",
    lodaing: "Connexion au réseau",
    again: "Réessayer...",
    tryOther: "Essayer un autre réseau",
    continue: "Continuer",
    connecting: "Connexion à",
    noConnectWifi: "Impossible de se connecter au wifi",
    noConnectInter: "Impossible de se connecter à Internet",
    succeeded: "Réussi",
  },
  bluetooth: {
    title: "Bluetooth",
    loading: "Connexion...",
    again: "Réessayer...",
    pair: "Appariement Bluetooth",
    waiting: "En attente de",
  },
  Renew: {
    noUpdate: "Pas encore de mise à jour",
    checkUpdate: "Vérification des mises à jour en ligne...",
    update: "Renouveler",
    Updatable: "Élément mis à jour",
    updateLoading: "Mise à jour en cours",
    retry: "Cliquez sur Réessayer",
    Retry: "Réessayer",
    failed: "Échec de l'élément",
    completed: "Terminé",
    updating: "Mise à jour, veuillez patienter",
    finish: "Terminer",
    fail: "Échec",
    reboot: "Redémarrer",
    hotUpdate: "Mise à jour rapide",
  },
};
