export default {
  account: {
    title: "Compte",
    nickname: "Nom",
    avatar: "Avatar",
    phone: "Téléphone",
    email: "E-mail",
    async: "Synchronisation des données",
    gallery: "Galerie de jeux",
    login: "Connexion",
    logout: "Déconnexion",
    info: "Pour les paramètres d'informations personnelles, il est recommandé d'aller à : ",
  },
  performance: {
    title: "Performances",
    presets: "Préréglages",
    newPreset: "Nouveau préréglage",
    fps: "Limite de FPS",
    tdp: "Limite de TDP",
    power: "Stratégie d'alimentation",
    fans: "Configuration des ventilateurs",
    cpu: "Verrouillage du CPU",
    gpu: "Verrouillage du GPU",
    Lock: "Verrouiller",
    frequency: "Turbo CPU",
    auto: "Automatique",
    lock: "Verrouiller",
    unlock: "Déverrouiller",
    more: "Détails",
    intelligence: "Intelligent",
    limit: "Illimité",
    saving: "Économie",
    balance: "Normal",
    hurricane: "Élevé",
    TDP: "Veuillez fermer Smart TDP",
    Disabled: "Smart TDP désactivé",
    After:
      "Après la désactivation de la consommation intelligente de TDP, elle ne peut pas être automatiquement restaurée, et une mise en veille manuelle S3 ou un redémarrage est nécessaire pour restaurer le contrôle de la puce vers le GPU",
    Sleep: "Veille S3",
    Reboot: "Redémarrer",
    Not: "Non désactivé",
    Enable: "Activer Smart TDP",
    turbo:
      "1. Désactivez la fréquence turbo : Sur AMD Ryzen 6800U, presque tous les jeux ont une performance CPU excessive, et lorsque la fréquence turbo est activée, le CPU gaspillera beaucoup de consommation d'énergie",
    power1:
      "2. La consommation d'énergie est réglée au maximum, comme 28W, et la consommation d'énergie intelligente réduira la consommation d'énergie. Lorsqu'elle est en cours, elle ne fonctionnera pas à pleine puissance",
    cannot:
      "3. Le jeu ne peut pas consommer toute la consommation d'énergie lorsque le nombre d'images est limité",
    complex:
      "4. Si le jeu rencontre des situations de rendu complexes, telles que le passage de scènes, le changement de résolution, etc., il faut environ 5 secondes pour stabiliser le taux de rafraîchissement, et les images chuteront et se figeront pendant ce processus",
    Turn: "Je comprends, Activer",
    NotAccept: "Non accepté",
    conditions: "Quatre conditions doivent être remplies pour que Smart TDP soit efficace :",
    fansConfig: {
      software: "Contrôle logiciel",
      hardware: "Contrôle matériel",
      algorithm: "Mode RPM",
      ladder: "Mode linéaire",
      linear: "Mode échelle",
      current: "Configuration actuelle :",
      self: "Configuration de vitesse - personnalité",
      tempAndSpeed: "Ajuster température et vitesse",
      switch: "Changer de nœuds",
      save: "Enregistrer les modifications",
      config: "Configuration RPM",
      mute: "Muet",
      balanced: "Équilibré",
      hurricane: "Max",
      personality: "Personnalisé",
      full: "100%",
      adjust: "Ajuster",
    },
    preinstall: {
      changeSort: "Changer l'ordre",
      rename: "Renommer",
      apply: "Utiliser le nouveau fichier de configuration",
      del: "Supprimer le fichier de configuration",
      naming: "Nommer le fichier de configuration",
      sort: "Configurer le tri",
      Cancel: "Annuler",
      Save: "Enregistrer",
      being: "Les informations de configuration sont en cours d'application",
    },
    map: {
      aaa: "Jeu AAA",
      classic: "Jeu normal",
      retro: "Jeu rétro",
      office: "Bureau PC",
    },
  },
  monitor: {
    title: "Moniteur",
    coating: "Superposition de performances",
    style: "Format",
    minimalism: "Simple",
    custom: "Personnalisé",
    list: {
      display: "Affichage des données",
      hard: "SSD",
      battery: "Alimentation",
      network: "Vitesse d'Internet",
      style: "Format",
      direction: "Vertical",
      broadwise: "Horizontal",
    },
    thirdParty: {
      detection: "Détection des dépendances tierces",
      title:
        "Cette fonction dépend des programmes tiers suivants \n ou des outils open source",
      rtssInfo:
        "Excellent logiciel OBS de surveillance matérielle, veuillez ne pas changer le chemin d'installation lors de l'installation",
      download: "Télécharger",
      installed: "Installé",
    },
  },
  launchOptimization: {
    title: "Démarrage & Optimisation",
    startup: "Démarrage",
    mouse: "Mode Souris",
    list: {
      full: "Désactiver le mode plein écran",
      gpu: "Mise à l'échelle du GPU",
      usb: "Comportement USB par défaut",
      osk: "Activer le clavier virtuel OSK",
      kernel: "Activer les cœurs du CPU",
      sleep: "Désactiver le mode veille",
      highest: "Activer les performances maximales",
      ram: "Vider la RAM",
    },
  },
  bluetooth: {
    title: "Bluetooth",
    other: "Bluetooth ou autres appareils",
    device: "Appareils",
  },
  wifi: {
    title: "Réseau",
    ethernet: "Ethernet",
    connection: "Réseau actuel : ",
    input: "Entrer le mot de passe du réseau ",
    password: ".",
    needPassword: "Le Wi-Fi nécessite un mot de passe",
    connecting: "Connexion au réseau en cours",
    detecting: "Détection de l'état du réseau",
    unable: "Impossible de se connecter au Wi-Fi",
    unableInternet: "Impossible de se connecter à Internet",
    successfully: "Connecté avec succès !",
    cancellation: "Annuler",
    try: "Essayer un autre réseau",
    success: "Succès",
    connect: "Connecter",
    device: "Réseaux disponibles",
  },
  BAW: {
    enable: "Activer ",
    disconnect: "Déconnecter",
    connect: "Connecter",
    connected: "Connecté",
    disconnected: "Déconnecté",
  },
  personalization: {
    title: "Personnalisation",
    theme: "Thème",
    systemWallpaper: "Fond d'écran",
    video: "Lire la vidéo",
    music: "Musique vidéo",
    effects: "Son",
    bgMusic: "BGM",
    Please: "Veuillez vous connecter à Internet pour obtenir un fond d'écran.",
    wallpaper: {
      download: "Téléchargement du fond d'écran",
      set: "Définir comme fond d'écran",
      error: "Échec du téléchargement",
      SetAs: "Définir comme fond d'écran",
      downloading: "Téléchargement",
      share: "Partager",
      full: "Plein écran",
      outFull: "Quitter le mode plein écran",
      wallpaper: "fond d'écran",
      Cutover: "Basculer",
    },
    themeInfo: {
      default: "Par défaut",
      dark: "Sombre",
      light: "Clair",
      auto: "Automatique",
      resetting: "Réinitialiser",
      bodyColor: "Couleur du texte",
      textAccent: "Couleur du sous-texte",
      background: "Couleur de fond",
      accent: "Couleur d'accentuation",
      reminder: "Alerte",
      button: "Bouton principal",
      focus: "Fenêtre active",
      icon: "Icône",
      preview: "Aperçu",
    },
  },
  generalSettings: {
    title: "Général",
    language: "Langue",
    languageTitle: "Langue",
    server: "Serveur",
    time: "Fuseau horaire",
    info: "Date",
    clear: "Nettoyer",
    Server: {
      china: "Chine ",
      global: "International ",
      tip: "Remarque : Le changement de serveur nécessite une nouvelle connexion",
    },
    Time: {
      date: "Date",
      time: "Heure",
      format: "Format de l'heure",
      zone: "Fuseau horaire",
      auto: "Ajustement automatique",
      year: "Année",
      month: "Mois",
      day: "Jour",
      hourly: " Mode horaire",
      getSuccess: "Obtention réussie",
      getError: "Échec de l'obtention",
    },
  },
  smallWindow: {
    title: "Fenêtres",
    menu: "Menu",
    sort: "Trier",
    smallSort: "Ordre des petites fenêtres",
    Sort: {
      Handheld: "Portatif",
      applet: "Mini-Application",
      handle: "Contrôleur Principal",
      set: "Assistant Rapide",
      system: "Système",
    },
  },
  controller: {
    title: "Contrôleur",
    resetting: "Réinitialiser",
    rocker: "Joystick",
    buttons: {
      title: "Personnaliser",
      japanese: "Japonais",
      standard: "Standard",
    },
    trigger: "Déclencheur analogique",
    felt: "Vibration",
    hair: "Automatique",
    gyroscope: "Gyroscope",
    key: "Bouton",
    correct: "Correction",
    adjustment: "Ajustement fin, expérience ultime.",
    according: "Laissez les touches changer selon vos habitudes",
    speed: {
      title: "Ouverture rapide",
      open: "Ouvert",
      unopened: "Fermé",
    },
    Keys: "=Bouton",
    rgb: "Effet d'éclairage RGB",
    custom: "Personnalisé",
    shoulder: "Bouton d'épaule personnalisé",
    continuously: {
      title: "Appuyez sur le bouton pour envoyer en continu",
      not: "Non disponible",
    },
    deadband: {
      title: "Zone morte du joystick",
      no: "Pas de zone morte",
      is: "Il y a une zone morte",
      Save: "Enregistrer et utiliser",
    },
    keys: {
      desktop: "Afficher le bureau",
      screenshot: "Capture d'écran",
      close: "Fermer le programme",
      keyboard: "Clavier",
      steam: "Ouvrir Steam",
      xbox: "Touches de navigation Xbox",
      view: "Vue des tâches",
      manager: "Gestionnaire des tâches",
      combinations: "Combinaisons de touches",
      program: "Ouvrir le programme",
      script: "Exécuter le script",
      toDesktop: "Équivalent à Win + D pour afficher le bureau du système.",
      UseScreenshot: "Utiliser la fonction de capture d'écran dans AYASpace.",
      toProgram:
        "Équivalent à l'opération ALT + F4, fermer le programme en cours.",
      Bring: "Afficher le clavier virtuel OSK, peut être utilisé.",
      ESC: "Touche ESC du clavier.",
      Software: "Lancer rapidement le logiciel Steam.",
      Equivalent:
        "Équivalent à la fonction de Win + G, après configuration, vous pouvez ouvrir l'assistant Xbox.",
      Tab: "Équivalent à Alt + Tab pour afficher rapidement les programmes ouverts.",
      enter:
        "Vous pouvez rapidement entrer dans l'entrée du gestionnaire des tâches ou effectuer une opération d'arrêt en douceur.",
      analog: "Combinaison personnalisée du déclencheur analogique et du clavier",
      Custom: "Application personnalisée",
      execution: "Code d'exécution de script personnalisé",
    },
    motor: {
      low: "Faible",
      middle: "Moyen",
      high: "Élevé",
      closed: "Fermé",
      violent: "Violent",
      soft: "Doux",
      custom: "Personnalisé",
      Vibration: "Vibration",
      Satisfy: "Satisfait la sensation de vibration de la plupart de vos jeux 3A",
      gentle:
        "Doux et doux, touche la paume, convient aux joueurs qui n'aiment pas la vibration forte.",
      favorite: "Explorez votre vibration préférée",
      Violent: "Violent",
    },
  },
  storage: {
    title: "Stockage",
    used: "Utilisé",
    common: "Total",
    format: "Formater la carte TF",
    confirm: "Confirmer le formatage de la carte TF",
    formatting: "Formatage",
    warn: "Veuillez noter que toutes les opérations sont irréversibles, veuillez opérer avec précaution.",
    success: "Carte TF formatée",
    failed: "Échec du formatage de la carte TF",
    disk: "SSD",
    tf: "Carte TF",
  },
  renew: {
    title: "Mise à jour",
    noUpdate: "Votre portatif est à jour.",
    log: "Journal des mises à jour",
    check: "Vérifier les mises à jour",
    allUpdate: "Mettre à jour tout",
    allInstall: "Installer tout",
    queue: "Voir la file d'attente",
    client: "Client",
    driver: "Pilotes",
    firmware: "Firmware",
    queueList: "File d'attente",
    oneRetry: "Un clic pour réessayer",
    updating: "Mise à jour en cours",
    completed: "Terminé",
    retry: "Réessayer",
    version: "Version",
    ignore: "Ignorer",
    updateCompleted: "Téléchargement terminé",
    install: "Installer",
    updateFailed: "Échec de la mise à jour",
  },
  about: {
    title: "À propos",
    hardware: "Matériel",
    name: "Nom de l'appareil",
    serial: "Numéro de série",
    system: "Système d'exploitation",
    cpuName: "Nom du CPU",
    frequency: "Fréquence du CPU",
    core: "Cœurs du CPU",
    memory: "RAM",
    monitor: "Version du logiciel",
    disk: "Numéro de série du SSD",
    inch: "Pouce",
    BIOSInfo: {
      name: "Nom",
      data: "Données",
    },
  },
  Default: {
    Default: "Par défaut",
    mono: "Respiration monochrome",
    RGB: "Respiration RGB",
    Google: "Respiration Google",
    Radar: "Radar",
    Ripple: "Ondulation",
    Always: "Lumière monochromatique toujours allumée",
    Brightness: "Luminosité",
    colour: "Couleur",
    mode: "Mode RGB",
    open: "Ouvrir la possibilité d'opérations plus rafraîchissantes",
    Load: "Charger le préréglage",
    custom: "Personnalisé",
    iterate:
      "Itérer avec les versions futures, la fonctionnalité de ce module changera, veuillez vous référer à la dernière version.",
    Off: "Éteindre les lumières",
    on: "Allumer les lumières",
    color: "Valeur de couleur hexadécimale (Hex)",
  },
  SetController: {
    Sensitivity: "Sensibilité",
    Left: "Joystick gauche",
    Right: "Joystick droit",
    Range: "Plage",
    Adjustment: "Ajustement de la plage",
    Have: "Ajustement de la plage disponible",
    No: "Aucun ajustement de la plage",
    Gyro: "Ajustement du gyroscope",
    Key: "Touche rapide",
    Low: "Faible",
    Medium: "Moyen",
    High: "Élevé",
    adjust: "Ajuster",
    off: "Éteint",
    Auto: "Auto",
    Burst: "Maintien en mode rafale",
  },
  illustrate: {
    Joystick: "Explication de la régulation du joystick / bouton",
    When: "Lorsque le joystick et LT / RT ne sont pas sensibles, vous pouvez essayer les opérations suivantes :",
    Press: "Appuyez sur les touches LB + RB + Dpad Gauche + B",
    handle: "Lorsque le contrôleur vibre,",
    rotate: "Rotation maximale de cinq tours.",
    upgrade: "Veuillez mettre à jour le firmware du contrôleur à la dernière version",
    Controller: "Le firmware du contrôleur peut être téléchargé via AYASpace",
    And: "Et mise à niveau selon le",
    Tutorial: "Tutoriel de mise à niveau",
    Up: "",
    press: "Appuyez simultanément sur",
    S: "S",
    Release: "Relâchez le bouton lorsque le contrôleur vibre.",
    double: "Les deux joysticks font une rotation complète au maximum,",
    trigger: "(Double déclencheur)",
    three: "Appuyez sur le bas trois fois.",
    calibration:
      "Lorsque l'étalonnage du contrôleur est terminé, le contrôleur vibrera en retour.",
  },
  control: {
    quick: "Contrôle rapide",
    for: "Raccourci Windows, accélérer à nouveau pour activer",
    gest: "Geste rapide",
    kb: "Touche AYA",
    Multitasking: "Multitâche",
    task: "Gestionnaire des tâches",
    Screenshot: "Capture d'écran",
    on: "Allumer",
    off: "Éteindre",
    while: "En maintenant enfoncé",
  },
  Button: {
    key: "= Bouton",
    open: "Ouvrir la possibilité d'opérations plus rafraîchissantes",
    keys: "Les touches personnalisées ne prennent effet que lorsque AYASpace est démarré,",
    not: "Lorsqu'il n'est pas démarré, le bouton par défaut est enfoncé brièvement : afficher le bureau.",
    short: "Appui court",
    Default: "Par défaut",
    show: "Afficher le bureau",
    osk: "Transférer OSK,",
    can: "Peut être utilisé.",
    Screenshot: "Capture d'écran",
    turn: "Éteindre l'application",
    Keyboard: "Clavier",
    Steam: "Allumer Steam",
    xbox: "Touche de navigation XBOX",
    task: "Vue des tâches",
    Manager: "Gestionnaire des tâches",
    Combination: "Combinaison de touches",
    program: "Ouvrir le programme",
    run: "Exécuter le script",
    iterate: "Itérer avec les versions futures",
    will: "La fonctionnalité de ce module changera,",
    refer: "Veuillez vous référer à la dernière version.",
    Reset: "Réinitialiser ",
    None: "Aucun",
    Used: "Utilisé",
    Paste: "Coller",
    Empty: "Vide",
    give: "Veuillez donner un nom à ce script",
    Program: "Ajouter un programme",
  },
  CustomKey: {
    Custom: "Touche personnalisée",
    Open: "Ouvrir la possibilité d'opérations plus rafraîchissantes",
    only: "Les touches personnalisées ne prennent effet que lorsque AYASpace est démarré,",
    not: "Lorsqu'il n'est pas démarré, le bouton par défaut est 'LC' appui court :",
    osk: "OSK / Appui long : Gestionnaire des tâches,",
    RC: "Appui court sur 'RC' :",
    ESC: "ESC / Appui long :",
    View: "Vue des tâches.",
    task: "Gestionnaire des tâches",
    key: "Combinaison de touches",
    Program: "Ouvrir le programme",
    run: "Exécuter le script",
    short: "Appui court",
    Long: "Appui long",
    OSK: "Transfert OSK, peut être utilisé.",
    iterate:
      "Itérer avec les versions futures, la fonctionnalité de ce module changera, veuillez vous référer à la dernière version.",
    Reset: "Réinitialiser ",
    enter:
      "Veuillez entrer la combinaison de touches que vous souhaitez utiliser sur la manette ou le clavier",
    Support: "Prise en charge de 1 à 4 boutons",
    select: "Veuillez sélectionner le programme que vous souhaitez démarrer",
    script: "Veuillez entrer votre script,",
    will: "Ce script sera exécuté une fois lorsque vous appuierez sur la touche",
  },
};
