export default {
  brandNew: "tout nouveau AYASpace 2.0",
  player: "Salut ! Joueur AYANEO",
  exclusive: "AYASpace est à toi",
  game: "Logiciel de gestion de contenu de jeux vidéo sur PC portable",
  Maybe: "Peut-être que tu n'es pas familier avec cela, ne t'inquiète pas. Passons maintenant par une configuration simple",
  next: "Étape suivante",
  press: "Appuyer longuement",
  Skip: "Ignorer le démarrage",
  Platform: "Gestion des jeux, Plateforme de jeux",
  helping: "Nous avons déjà trié les informations locales sur les jeux pour toi",
  scan: "Analyse des jeux locaux",
  still: "Si tu as toujours une plateforme de jeu à installer, tu peux en choisir plusieurs à droite, et nous t'aiderons à les télécharger",
  download: "Suivant et télécharge la plateforme de jeu sélectionnée",
  work: "Finalisation du travail final",
  Enjoy: "Profite de ton AYANEO",
  GoTo: "Aller vers le jeu amusant !",
  complete: "terminé",
  Start: "Commencer l'optimisation",
  Guide: "Terminer le guide du débutant",
  toggle: "basculer",
  Selected: "Sélectionné",
  many: "nombreux",
  Press: "appuyer",
  mark: "marquer",
};
