export default {
  myApp: "Moja aplikacje",
  _myApp: "Software",
  Y: "Uruchom",
  Renew: "Odnów",
  install: "„Zainstaluj”",
  emulator: "Emulator",
  platform: "„Platforma”",
  empty: "Twoja lista aplikacji jest pusta.",
  uninstall: "Odinstaluj",
  development: "Dewelopment",
  system: "System",
  other: "Inne",
  apperror: "Uruchomienie oprogramowania nie powiodło się",
  updateError: "Aktualizacja nie powiodła się",
  installError: "Instalacja nie powiodła się",
  noApp: "Nie znaleziono aplikacji",
  nowifi: "Nie znaleziono aplikacji, spróbuj ponownie",
};
