export default {
  sort: "Sort",
  run: "Launch",
  flod: "Close",
  empty: "Empty",
  openSteam: "Open Steam",
  manage: "Manage",
  gameIsRunning: "Game already running",
  Confirm: "Confirm",
  QFind: {
    pc: "Installed Games",
    initials: "Initials",
    label: "Label",
    platform: "Platform",
    type: "Type",
    publish: "Publisher",
    manufacturer: "manufacturer",
    removeAll: "remove all",
    selected: "selected",
    item: "",
    common: "Total",
  },
  SortPopups: {
    layout: "Layout",
    largeGrid: "Grid Mode",
    DetailsList: "List Mode",
    columns: "Columns",
    sort: "Sort",
    Playtime: "By Time Played",
    StorageTime: "By Date Added",
    gameName: "By Name",
    Ascending: "Ascending Order",
    Descending: "Descending Order",
    buttonX: "Application",
  },
  GameDefault: {
    noGame: "No game yet",
    steam: "Steam game installation and import",
    other: "Other PC game installation and import",
    retro: "Retro Game Import",
    select: "select",
    supportSystem: "Support System",
    GameTransferProcess: "Game transfer",
    Disclaimer: "Disclaimer",
    nostalgia:
      "AYANEO OS nostalgic library is only a content management tool and does not provide Roms and BIOS.",
    privateGame:
      "The private game imported by you in the AYANEO OS nostalgic library, please ensure that you have the right to use the game, and the game copyright belongs to the game publisher and game production team",
    gameModification:
      "AYANEO OS does not assume any responsibility for the consequences of players' operations such as game modification and deletion",
    coming: "coming soon",
  },
  GameDetails: {
    from: "From",
    installed: "Installed",
    gameTime: "Game Time",
    h: "h",
    data: "Options",
    playGame: "Launch",
    settings: "Emulator",
    video: "Video",
    hour: "Hour(s)",
    Art: "Art Wall",
    Cutover: "Cutover",
    Full: "Full Screen",
    outFull: "Exit Full Screen",
    Play: "Play",
    Stop: "Stop",
    noVideo: "Temporarily no video",
    noWall: "Temporarily no wall art data",
  },
  GameManage: {
    currentData: "Current Game Data",
    hide: "hide",
    Hidden: "Hidden",
    data: "Data",
    search: "Manual Search",
    remove: "Remove Record",
    uninstall: "Uninstall Game",
    noFound: "No matching results were found.",
    search1: "total",
    search2: "game data found",
    hideGame: "hide this game",
    uninstallGame: "Do you want to uninstall this game",
    removeGame: "Do you want to remove games and records",
    SecondConfirmation: "Use this piece of data as game display information?",
    isSuccess: "Success",
    isError: "Error",
    mod: "Data modification",
    // space
    cloudData: "Cloud Data",
    deleteGame: "Delete Game",
    removeLibrary: "Remove From Library",
    del: "Game deleted",
    failed: "Game deletion failed",
    removed: "Game Removed",
    Whether: "Whether to use this piece of data as game display information?",
    toHide: "Whether to hide this game",
    toShow: "whether to show this game",
    deleted: "Successfully Deleted",
    fled: "Delete Failed",
  },
  // space 游戏管理 根据文件名区分
  management: {
    title: "Game Management",

    firstName: {
      addGame: "Add Games",
    },
    lastName: {
      uninstall: "Uninstall Game",
      unknownFile: "Potential Game Files",
    },
    manageIndex: {
      title1: "Manage your private game collection",
      title2: "Enjoy unprecedented control",
      addGame: "Add Game",
      games: "Games",
      uninstall: "Uninstall Game",
      suspectedGame: "Potential Game Files",
      none: "None",
      unknowFile: "Unknown Game Management",
      Manual: "Manual Addition",
      Hidden: "Hidden Items",
      hide: "Hidden",
    },
    winAddGame: {
      newGame: "New Game",
      scanGame: "Scan Games",
    },
    winDelGame: {
      select1: "Select the games that you want to ",
      uninstall: "uninstall",
      select2: "",
      mark: "Select",
      press: "Long Press to Uninstall",
      total: "Total Selected",
      games: "Games",
      Uninstall: "Whether to uninstall the selected game?",
    },
    winHandAdd: {
      isGameFile: "Which of the following are game files ?",
      tryLaunch: "Try to Launch",
      // games: "games",
      // file: "File ?",
      FileLocation: "File Location:",
      TextMessage4: "The selected file is already",
      added: "added",
      library: "Go to the game library",
      longPress: "Long Press Exclude",
      launch: "Try to Launch",
      select: "Please select the game launch file",
      common: "Common Directory",
      add: "Add Directory",
      remove: "Remove Directory",
      Scanning: "Scanning...",
      Rescan: "Rescan",
      Scan: "Scan Failed",
      AddGame: "Scan complete，Add new game:",
      current: "Save the current directory",
      Previous: "Previous directory",
      Enter: "Enter directory",
      Close: "Close checkbox",
      Back: "Back to previous",
      whether: "whether to remove the directory",
      Installed: "There are no installed games",
      try: "Use the",
      management: "game management",
      designed: "feature to add games.",
      Start: "to launch game management",
      Added: "Added to Installed Games",
    },
    data: {
      Management: "Data Management",
      Modification: "Data Modification",
      name: "Game Name",
      Describe: "Describe",
      label: "Game Label",
      add: "Add Label",
      logo: "Game LOGO",
      cover: "Game Cover",
      back: "Game Background",
      save: "Save",
      cancellation: "Cancellation",
      Uploading: "Uploading",
      Notice: "Notice",
      noNotice: "Temporarily no notice.",
      modified: "Successfully modified",
      All: "Read All",
      Clear: "Clear Record",
    },
    home: {
      run: "Running Game",
      enjoy: "Enjoy your game",
      Close: "Close",
      exit: "Exit Game",
      continue: "Continue Game",
      Expand: "Expand",
      Running: "Running",
      s: "S",
      failed: "Failed to start the game,Please check the game launcher",
      an: "Press",
      open: "to open the launcher",
      game: "Close Game",
      start: "Preparing to start",
      wait: "Wait",
    }
  },
};
