export default {
  title: "Asystent",
  fast: "Szybko",
  file: "Plik",
  community: "Społeczność",
  gallery: "Galeria",
  closed: "Zamknięte",
  activated: "Aktywowane",
  upadte: "Aktualziacja",
  hasUpdate: "Może być aktualizowany",
  pc: "Poznaj możliwości handheldów PC",
  emulator_: "Emulator",
  setUp: "Ustawienia",
  master1: "Master Controller",
  master2: "Niezrównane poczucie kontroli",
  master3: "Konfiguracja trybu pracy",
  emulator: {
    global: "Globalny",
    Independent: "Niezależny",
    expand: "Rozciągnięty",
    shrink: "Przycięty",
    advanced: "Zawansowany",
    emulator_core: "Rdzeń Emulatora",
    ratio: "Ratio",
    videomodel: "Model Wideo",
    shaderset: "Zestaw shaderów",
    bezel: "Ramka",
    gfxbackend: "API graficzne",
    refreshGame: "Odśwież listę gier",
    refresNow: "Odśwież teraz",
    refreshSuccess: "Odświeżenie zakończone skukcesem",
    refreshFailed: "Odświeżenie nie powiodło się",
  },
  GameGallery: {
    sync: "Synchronizacja automatyczna",
    null: "Twoja galeria jest pusta",
    openList: "Otwórz listę",
  },
  EjectImg: {
    loading: "wgrywam...",
    error: "Wgranie nie powiodło się",
    Retry: "Spróbuj jeszcze raz",
    qrcode1: "Zeskanuj kod QR",
    qrcode2: "Zobacz zrzuty ekrnanów z gier",
    del: "Usunięcie powiodło się",
  },
  Message: {
    title: "Instructions and reminders",
    text1:
      "You are preparing to enable the automatic screenshot upload function, which provides a better experience for you to share game screenshots. At the same time, the uploaded screenshot data will be saved in your personal database on the AYANEO server. The use of data and synchronization functions requires your consent. Please read carefully",
    agreement: "《Software License Agreement》",
    privacy: "《Privacy Policy》",
    text2:
      ", turning on this feature will mean that you understand and understand our relevant policies.",
    true: "I understand, turn this feature on",
    false: "Do not accept",
    and: "And",
  },
  AYAlink: {
    title: "WiFi Transfer",
    nowWifi: "current network:",
    hink: "Please use a browser under the same network to access",
    off_: "Service is down",
    wait: "Service is on",
    on: "ON",
    off: "OFF",
    password: "The initial account password is: ayaneo",
  },
};
