export default {
  model: "model",
  total: "Time Played: ",
  power: "power mode ",
  temperature: "℃",
  wifiNoConnected: "Wifi Not Connected",
  openWifi: "turn on wifi",
  bluetooth: "Bluetooth",
  gameMode: "Game",
  balanced: "Equal",
  saving: "Saving",
  home: "Home",
  PCGames: "Installed Games",
  hour: "Hour(s)",
  Select: "Select",
  Confirm: "Confirm",
  default: {
    welcome: "Welcome",
    p1: "No game yet, Please log in to steam to download your game",
    p2: "Or import other games",
    startUp: "Start Up",
    howRetro: "How Import Retro Games",
  },
  second: {
    fracticon: "High marks will play",
    noPlay: "High Score Must Play",
    noWifi1: "Please connect to the Internet to get game data Press",
    noWifi2: "Open Network Settings",
  },
};
