export default {
  performance: {
    Performance: "Performance",
    Lock: "FPS Limit",
    Trimmer: "TDP Limit",
    Float: "Performance Overlay",
    style: "Format",
    Simple: "Simple",
    custom: "Custom",
    fan: "Fan Configuration",
    software: "Software Control",
    hardeare: "Hardware Control",
    Unlimited: "Unlimited",
    Config: "RPM Config",
    Mode: "Ladder Mode",
    Mode1: "RPM Mode",
    Mode2: "Linear Mode",
    Mute: "Mute",
    Balanced: "Balanced",
    max: "Max",
    Custom: "Custom",
    qsw: "100%",
    FPSsome: "In some cases, limiting to the target frame rate can stabilize FPS, but it is recommended not to limit. This function invokes the AMD driver, and this function will be invalid when using RSR.",
    TDPQuickly: "Quickly adjust TDP to help you get a better experience in the games you are running.",
    Exclusive: "Exclusive FPSThunder is recommended for an excellent experience. You need to install dependent libraries for the first use, please install/repair according to the prompts.",
    dissatisfied: "If you are dissatisfied with the noise of the machine running, you can flexibly adjust the fan strategy according to your personal situation.",
  },
  controller: {
    Controller: "Controller",
    Vibration: "Vibration",
    custom: "Custom",
    Low: "Low",
    Middle: "Medium",
    High: "High",
    Close: "Off",
    violent: "violent",
    soft: "soft",
    Trigger: "Analog Trigger",
    Sensitivity: "Sensitivity",
    Joystick: "Joystick",
    mode: "Range Adjustment",
    Custom: "Custom",
    model: "ABXY Mode",
    Normal: "Normal",
    Japanese: "Japanese",
    fully: "Fully Automatic",
    semi: "Semi Automatic",
    Non: "Non recurrent hair",
    Gyro: "Gyro",
    adjus: "Gyro Adjustment",
    StartKey: "Quick Key",
    RGB: "RGB Mode",
    Switch: "Enable",
    Mode1: "Mode",
    Brightness: "Brightness",
    Automatic: "Auto",
    Gamepad: "Disable Controller",
    Reset: "Reset",
    Default: "Default",
    breath: "Monochrome Breathe",
    loop: "RGB Breathe",
    goole: "Google Breathe",
    Scanning: "Radar",
    Repple: "Ripple",
    always: "Monochromatic Always On",
    LeftJoy: "Left Joystick",
    RightJoy: "Right Joystick",
    XBOX: "XBox standard keys",
    swap: "AB / XY key swap，SNES layout",
    sensitivity: "Set the sensitivity you want for the two trigger keys, he will give you a smooth operating experience",
    joysticks: "Set the sensitivity you want for the two joysticks, it will be more in line with your operating habits",
    down: "Hold down the button, Burst of 20 times/s",
    Click: "Click it once,Automatic burst,Press again to stop;"

  },
  psp: {
    Handheld: "Handheld Options",
    Brightness: "Brightness",
    Volume: "Volume",
    mode: "Airplane Mode",
    Bluetooth: "Bluetooth",
    WIFI: "Wi-Fi",
    Mute: "Mute",
    screen: "Download With Screen Off",
  },
  quickSetup: {
    quick: "Quick Assistant",
    quicktool: "Quick Settings Management",
    win: "Win",
    game: "Close Game",
    osk: "OSK",
    Mute: "Mute",
    Hibernate: "Hibernate",
    WIFI: "Wi-Fi",
    Bluetooth: "Bluetooth",
    USB: "USB Controller",
    full: "Fullscreen ",
    Minimize: "Minimize",
    mouse: "Joystick Mode",
    Optional: "Optional",
    Screenshot: "Screenshot",
    Vibration: "Vibration",
    mode: "Airplane Mode",
    Reset: "Reset",
    Done: "Accept",
    Remove: "Remove",
    Gamepad: "Disable Controller",
    multitasking: "Multitasking",
    GameOverlay: "Game Overlay",
    increase: "Add More",
    Undefined: "Undefined",
    Mouse: "Simulated Mouse",
    ESC: "ESC",
    FSR: "FSR",
  },
  settings: {
    System: "System",
    aya: "AYANEO Handheld",
    check: "Check Updates",
    Systems: "System Settings",
    FAQ: "FAQ",
    windows: "Windows Options",
    task: "Task Manager",
    device: "Device Manager",
    control: "Control Panel",
    file: "File Manager",
    set: "Windows Settings",
    display: "Windows Settings",
    Update: "No Update",
    Immediately: "Immediately",
  }
};
