export default {
  center: {
    quickSet: "Quick Setup",
    power: "Current power",
    handle: "",
    tool: "Emulator tool",
    menu: "Menu",
    filter: "Toggle Filter",
    rebot1: "Rebot",
    rebot2: "Game",
    rebot3: "Software",
    add: "Add widget",
    fan: "Fan",
    auto: "Auto",
    simple: "Simple",
    ordinary: "Ordinary",
    A_: "Removed",
    screenshotSucces: "The screenshot was successful",
  },
  component: {
    management: "Control Management",
    optional: "Optional",
    quickControl: "Quick Control",
    added: "Added",
    gyro: "Gyro",
    sensitivity: "Sensitivity",
    startKey: "Start key",
    press: "Press",
    gyroAiming: "Auto Start Gyro Aiming",
    windowManagement: "Widget Control Management",
    archive: "Archive",
    middle: "Middle",
    low: "Low",
    high: "High",
  },
};
