export default {
  connect: "Connect",
  connected: "Connected",
  disconnect: "Disconnect",
  noconnect: "Not connected",
  open: "Open",
  self: {
    title: "Assistant",
    setUp: "Set Up",
    account: "Account",
    bluetooth: "Bluetooth",
    themeSettings: "Theme",
    language: "Language",
    timeZone: "Time Zone",
    server: "Server",
    aboutDevice: "Device Info",
    library: "Third Librs",
    renew: "Renew",
    Activated: "Activated",
    Unopened: "Unopened",
    noRenew: "No update",
    hasRenew: "Updates",
  },
  aboutDevice: {
    text: "Device Name",
    version: "Version",
    storage: "Storage",
    available: "Available",
    all: "Common",
    model: "Device model",
    serial: "Serial Number",
    software: "Software Version",
  },
  ThemeSettings: {
    settingsTheme: "Theme settings",
    playVideo: "Play video",
    videoMusic: "Video music",
    system: "System",
    soundEffect: "Sound effect",
    backgroundMusic: "Background music",
  },
  AboutAccount: {
    title: "Account security",
    name: "Nick name",
    avatar: "Avatar",
    phone: "Phone number",
    message: "Personal information settings, recommended",
    noLogin: "Not logged in",
    signOut: "Sign out",
    login: "Log in",
    isSure: "Confirm logout?",
  },
  FormatTF: {
    title: "Format TF card",
    operate: "Confirm to format the TF card",
    warning: "Please proceed with caution.",
    success: "Formatted TF card",
  },
  SecondConfirmation: {
    Whether: "Whether to ",
  },
  reset: {
    title: "Restore factory settings",
    data: "Retain game data and restore system settings",
    noData: "Clear all local data and restore system settings",
  },
  timer: {
    timerTitle: "Time",
    Automatic: "Auto",
    date: "Date",
    year: "Year",
    month: "Month",
    day: "Day",
    timeFormat: "Time format",
    HourSystem: "Hour system",
    confirm: "Confirm",
    timeZone: "Time zone",
    twenty: "24 hour clock",
    twelve: "12 hour clock",
    am: "AM",
    pm: "PM",
    AutoSuccess: "Obtained automatically",
  },
  servers: {
    serversTitle: "Connection Server",
    zh: "Chinese server",
    en: "International server",
    msg: "You need to log in again after switching servers",
  },
  wifi: {
    wifiTitle: "Network",
    nowWifi: "Now Network:",
    off_: "Disconnected",
    password: "Password",
    input: "",
    wifiPassword: "",
    error: "Wrong password, please re-enter",
    HoldOn: "Hold on",
    lodaing: "Connecting to network",
    again: "try again...",
    tryOther: "try another network",
    continue: "Continue",
    connecting: "Connecting to",
    noConnectWifi: "Can't connect to wifi",
    noConnectInter: "Can't connect to the internet",
    succeeded: "Succeeded",
  },
  bluetooth: {
    title: "Bluetooth",
    loading: "connecting...",
    again: "try again...",
    pair: "Bluetooth pairing",
    waiting: "Waiting for",
  },
  Renew: {
    noUpdate: "No update yet",
    checkUpdate: "Checking for updates online. . .",
    update: "Renew",
    Updatable: "Item updated",
    updateLoading: "Updating",
    retry: "Click retry",
    Retry: "Retry",
    failed: "Item failed",
    completed: "Finish",
    updating: "Updating, please wait",
    finish: "Finish",
    fail: "Fail",
    reboot: "Reboot",
    hotUpdate: "Hot update",
  },
};
