export default {
  account: {
    title: "Account",
    nickname: "Name",
    avatar: "Avatar",
    phone: "Phone",
    email: "E-mail",
    async: "Data Sync",
    gallery: "Game Gallery",
    login: "Login",
    logout: "Sign Out",
    info: "For personal info settings, it is recommended to go to: ",
  },
  performance: {
    title: "Performance",
    presets: "Preset",
    newPreset: "New preset",
    fps: "FPS Limit",
    tdp: "TDP Limit",
    power: "Power Policy",
    fans: "Fan Configuration",
    cpu: "CPU Lock",
    gpu: "GPU Lock",
    Lock: "Lock",
    frequency: "CPU Turbo",
    auto: "Auto",
    lock: "Lock",
    unlock: "unlock",
    more: "Detailed",
    intelligence: "Smart",
    limit: "Unlimited",
    saving: "Saving",
    balance: "Normal",
    hurricane: "High",
    TDP: "Please Close Smart TDP",
    Disabled: "Disabled Smart TDP",
    After:
      "After the Smart TDP consumption is disabled, it cannot be automatically restored, and manual S3 sleep or restart is required,to restore control of the chip to the GPU",
    Sleep: "S3 Sleep",
    Reboot: "Reboot",
    Not: "Not Disabled",
    Enable: "Enable Smart TDP",
    turbo:
      "1、Turn off turbo frequency: On AMD Ryzen 6800U, almost all games have excess CPU performance, and when turbo frequency is turned on, the CPU will waste a lot of power consumption",
    power1:
      "2、The power consumption is set to the maximum, such as 28W, and the smart power consumption will reduce the power consumption. When it is in effect, it will not run to full power consumption",
    cannot:
      "3、The game cannot consume all the power consumption when the number of frames is limited",
    complex:
      "4、If the game encounters complex rendering situations, such as switching scenes, changing resolution, etc., it takes about 5 seconds to stabilize the frame rate, and frames will drop and freeze during this process",
    Turn: "I understand, Turn on",
    NotAccept: "Not Accept",
    conditions: "Four conditions need to be met for Smart TDP to take effect:",
    fansConfig: {
      software: "Software Control",
      hardware: "Hardware Control",
      algorithm: "RPM Mode",
      ladder: "Linear Mode",
      linear: "Ladder Mode",
      current: "Current configuration:",
      self: "Speed configuration - personality",
      tempAndSpeed: "Adjusting temperature and speed",
      switch: "Switch nodes",
      save: "Save Changes",
      config: "RPM Config",
      mute: "Mute",
      balanced: "Balanced",
      hurricane: "Max",
      personality: "Custom",
      full: "100%",
      adjust: "Adjust",
    },
    preinstall: {
      changeSort: "Change Order",
      rename: "Rename",
      apply: "Use New Config File",
      del: "Delete Config File",
      naming: "Name Config File",
      sort: "Configure sorting",
      Cancel: "Cancel",
      Save: "Save",
      being: "The configuration information is being applied",
    },
    map: {
      aaa: "AAA Game",
      classic: "Normal Game",
      retro: "Retro Game",
      office: "PC Office",
    },
  },
  monitor: {
    title: "Monitor",
    coating: "Performance Overlay",
    style: "Format",
    minimalism: "Simple",
    custom: "Custom",

    list: {
      display: "Data Display",
      hard: "SSD",
      battery: "Power",
      network: "Internet Speed",
      style: "Format",
      direction: "Vertical",
      broadwise: "Horizontal",
    },

    thirdParty: {
      detection: "Detect third-party dependencies",
      title:
        "This feature relies on the following third-party programs \n or open source tools",
      rtssInfo:
        "Excellent hardware monitoring OBS software, please do not change the installation path during installation",
      download: "Download",
      installed: "Installed",
    },
  },
  launchOptimization: {
    title: "Startup & Optimization",
    startup: "Startup",
    mouse: "Mouse Mode",

    list: {
      full: "Disable Fullscreen",
      gpu: "GPU Scaling",
      usb: "Default USB Behavior",
      osk: "Enable OSK",
      kernel: "Enable CPU Cores",
      sleep: "Disable Sleep Mode",
      highest: "Enable Maximum Performance",
      ram: "Clear RAM",
    },
  },
  bluetooth: {
    title: "Bluetooth",
    other: "Bluetooth or Other Devices",
    device: "Devices",
  },
  wifi: {
    title: "Network",
    ethernet: "Ethernet",
    connection: "Current Network: ",
    input: "Enter the network password of ",
    password: ".",
    needPassword: "Wi-Fi requires a password",
    connecting: "Connecting to the network",
    detecting: "Detecting network status",
    unable: "Unable to connect to Wi-Fi",
    unableInternet: "Unable to connect to the internet",
    successfully: "Successfully connected!",
    cancellation: "Cancel",
    try: "Try another network",
    success: "Success",
    connect: "Connect",
    device: "Available Networks",
  },
  BAW: {
    enable: "Enable ",
    disconnect: "Disconnect",
    connect: "Connect",
    connected: "Connected",
    disconnected: "Disconnected",
  },
  personalization: {
    title: "Customize",
    theme: "Theme",
    systemWallpaper: "Wallpaper",
    video: "Play Video",
    music: "Video Music",
    effects: "Sound",
    bgMusic: "BGM",
    Please: "Please connect to the Internet to obtain wallpaper.",
    wallpaper: {
      download: "Downloading wallpaper",
      set: "Set as wallpaper",
      error: "Download failed",
      SetAs: "Set Wallpaper",
      downloading: "Download",
      share: "Share",
      full: "Full screen",
      outFull: "Exit Full Screen",
      wallpaper: "wallpaper",
      Cutover: "Cutover",
    },

    themeInfo: {
      default: "Default",
      dark: "Dark",
      light: "Light",
      auto: "Auto",
      resetting: "Reset",
      bodyColor: "Text Color",
      textAccent: "Sub Text Color",
      background: "Background Color",
      accent: "Accent Color",
      reminder: "Alert",
      button: "Main Button",
      focus: "Focused Window",
      icon: "Icon",
      preview: "Preview",
    },
  },
  generalSettings: {
    title: "General",
    language: "Language",
    languageTitle: "Language",
    server: "Server",
    time: "Time Zone",
    info: "Date",
    clear: "Clean",

    Server: {
      china: "China ",
      global: "International ",
      tip: "Note: Switching servers requires Log in again",
    },

    Time: {
      date: "Date",
      time: "Time",
      format: "Time format",
      zone: "Time zone",
      auto: "Automatic Adjustment",
      year: "Year",
      month: "Month",
      day: "Day",
      hourly: " Hour Mode",
      getSuccess: "Successfully Obtained",
      getError: "Acquisition Failed",
    },
  },
  smallWindow: {
    title: "Windows",
    menu: "Menu",
    sort: "Sort",
    smallSort: "Small Window Order",

    Sort: {
      Handheld: "Handheld",
      applet: "Mini-App",
      handle: "Master Controller",
      set: "Quick Assistant",
      system: "System",
    },
  },
  controller: {
    title: "Controller",
    resetting: "Reset",
    rocker: "Joystick",
    buttons: {
      title: "Custom",
      japanese: "Japanese",
      standard: "Standard",
    },
    trigger: "Analog Trigger",
    felt: "Vibration",
    hair: "Auto",
    gyroscope: "Gyro",
    key: "Button",
    correct: "Correct",
    adjustment: "Fine adjustment,Ultimate experience.",
    according: "Let the keys change according to your habits",
    speed: {
      title: "Quick Open",
      open: "Opened",
      unopened: "Unopened",
    },
    Keys: "=Button",
    rgb: "RGB lighting effect",
    custom: "Custom",
    shoulder: "Custom Shoulder Key",
    continuously: {
      title: "Press button to send continuously",
      not: "Not have",
    },
    deadband: {
      title: "Rocker Deadband",
      no: "No dead zone",
      is: "There is a dead zone",
      Save: "Save&Use",
    },
    keys: {
      desktop: "Show Desktop",
      screenshot: "Screenshot",
      close: "Close Program",
      keyboard: "Keyboard",
      steam: "Open Steam",
      xbox: "Xbox Nav Keys",
      view: "Task View",
      manager: "Task Manager",
      combinations: "Key Combinations",
      program: "Open Program",
      script: "Run Script",
      toDesktop: "Equivalent to Win + D to display the system desktop.",
      UseScreenshot: "Use the screenshot function in AYASpace.",
      toProgram:
        "Equivalent to the operation of ALT + F4, close the current program.",
      Bring: "Bring up the OSK, can use.",
      ESC: "Keyboard's ESC key.",
      Software: "Quick Launch Steam Software.",
      Equivalent:
        "Equivalent to the function of Win + G, After configuration, You can open the Xbox Assistant.",
      Tab: "Equivalent to Alt + Tab to quickly view open programs.",
      enter:
        "You can quickly enter the entry of the task manager, or perform a soft shutdown operation.",
      analog: "Custom analog trigger combination keyboard",
      Custom: "Custom open application",
      execution: "Custom execution script code",
    },
    motor: {
      low: "Low",
      middle: "Middle",
      high: "High",
      closed: "Closed",
      violent: "Violent",
      soft: "Soft",
      custom: "Custom",
      Vibration: "Vibration",
      Satisfy: "Satisfy the vibration feeling of most of your 3A games",
      gentle:
        "Soft and gentle, touching the palm, suitable for Gamers who don't like strong vibration.",
      favorite: "Explore your favorite vibration",
      Violent: "Violent",
    },
  },
  storage: {
    title: "Storage",
    used: "Used",
    common: "Total",
    format: "Format TF card",
    confirm: "Confirm formatting TF card",
    formatting: "Formatting",
    warn: "Please note that all operations are irreversible, please operate with caution.",
    success: "Formatted TF card",
    failed: "Format TF card failed",
    disk: "SSD",
    tf: "TF card",
  },
  renew: {
    title: "Update",
    noUpdate: "Your handheld is up to date.",
    log: "Update Log",
    check: "Check Update",
    allUpdate: "Upgrade All",
    allInstall: "Install All",
    queue: "View queue",
    client: "Client",
    driver: "Drivers",
    firmware: "Firmware",
    queueList: "Queue",
    oneRetry: "One click retry",
    updating: "Updating",
    completed: "Completed",
    retry: "Retry",
    version: "Version",
    ignore: "Ignore",
    updateCompleted: "Download completed",
    install: "Install",
    updateFailed: "Update failed",
  },
  about: {
    title: "About",
    hardware: "Hardware",
    name: "Device Name",
    serial: "Serial Number",
    system: "OS",
    cpuName: "CPU Name",
    frequency: "CPU Frequency",
    core: "CPU Cores",
    memory: "RAM",
    monitor: "Software Version",
    disk: "SSD Serial",
    inch: "Inch",

    BIOSInfo: {
      name: "Name",
      data: "Data",
    },
  },
  Default: {
    Default: "Default",
    mono: "Monochrome Breathe",
    RGB: "RGB Breathe",
    Google: "Google Breathe",
    Radar: "Radar",
    Ripple: "Ripple",
    Always: "Monochromatic Always On",
    Brightness: "Brightness",
    colour: "Colour",
    mode: "RGB Mode",
    open: "Open up the possibility of more refreshing operations",
    Load: "Load preset",
    custom: "Custom",
    iterate:
      "Iterate with future versions,The functionality of this module will change,Please refer to the latest version.",
    Off: "Turn Off Lights",
    on: "Turn on the lighting",
    color: "Hexadecimal color value（Hex）",
  },
  SetController: {
    Sensitivity: "Sensitivity",
    Left: "Left Joystick",
    Right: "Right Joystick",
    Range: "Range",
    Adjustment: "Range Adjustment",
    Have: "Have Range Adjustment",
    No: "No Range Adjustment",
    Gyro: "Gyro Adjustment",
    Key: "Quick Key",
    Low: "Low",
    Medium: "Medium",
    High: "High",
    adjust: "Adjust",
    off: "Off",
    Auto: "Auto",
    Burst: "Hold Burst",
  },
  illustrate: {
    Joystick: "Joystick / Button Regulate Explain",
    When: "When the joystick and LT / RT are not sensitive, you can try the following operations:",
    Press: "Press LB + RB + Dpad Left + B keys",
    handle: "When the handle controller vibrates,",
    rotate: "Maximum rotation of five turns。",
    upgrade: "Please upgrade the handle firmware to the latest version",
    Controller: "Controller firmware can be downloaded via AYASpace",
    And: "And upgrade according to the",
    Tutorial: "Upgrade Tutorial",
    Up: "",
    press: "Simultaneously press",
    S: "S",
    Release: "Release the button when the handle controller vibrates.",
    double: "The double joystick rotates one circle to the maximum,",
    trigger: "(Double trigger)",
    three: "Press bottom three times.",
    calibration:
      "When the handle calibration is completed, the handle controller will vibrate for feedback.",
  },
  control: {
    quick: "Quick Control",
    for: "Windows shortcut, speed up again to drive",
    gest: "Quick Gesture",
    kb: "AYA Key",
    Multitasking: "Multitasking",
    task: "Task Manager",
    Screenshot: "Screenshot",
    on: "Turn On",
    off: "Turn Off",
    while: "While Holding Down",
  },
  Button: {
    key: "= Button",
    open: "Open up the possibility of more refreshing operations",
    keys: "Custom keys only take effect when AYASpace is started,",
    not: "When not started, the default button is short press: display the desktop。",
    short: "Short Press",
    Default: "Default",
    show: "Show Desktop",
    osk: "Transfer OSK,",
    can: "Can Use.",
    Screenshot: "Screenshot",
    turn: "Turn Off App",
    Keyboard: "Keyboard",
    Steam: "Turn on Steam",
    xbox: "XBOX Navigation key",
    task: "Task View",
    Manager: "Task Manager",
    Combination: "Key Combination",
    program: "Open Program",
    run: "Run Script",
    iterate: "Iterate with future versions",
    will: "The functionality of this module will change,",
    refer: "Please refer to the latest version.",
    Reset: "Reset ",
    None: "None",
    Used: "Used",
    Paste: "Paste",
    Empty: "Empty",
    give: "Please give this script a name",
    Program: "Add Program",
  },
  CustomKey: {
    Custom: "Custom Key",
    Open: "Open up the possibility of more refreshing operations",
    only: "Custom keys only take effect when AYASpace is started,",
    not: "When not started, the default button is 'LC'  short press:",
    osk: "OSK / Long press: Task Manager,",
    RC: "'RC' Short press:",
    ESC: "ESC / Long press:",
    View: "Task View.",
    task: "Task Manager",
    key: "Key combination",
    Program: "Open Program",
    run: "Run Script",
    short: "Short Press",
    Long: "Long press",
    OSK: "Transfer OSK,Can Use.",
    iterate:
      "Iterate with future versions,The functionality of this module will change,Please refer to the latest version.",
    Reset: "Reset ",
    enter:
      "Please enter the key combination you want to use on the handle or keyboard",
    Support: "Support 1-4 buttons",
    select: "Please select the program you want to start",
    script: "Please enter your script,",
    will: "This script will be executed once when you press the key",
  },
};
