export default {
  brandNew: "brand new AYASpace 2.0",
  player: "Hello! AYANEO player",
  exclusive: "AYASpace Is yours",
  game: "PC handheld game content management software",
  Maybe: "Maybe you're not familiar with it, don't worry Now let's go through some simple setup",
  next: "Next step",
  press: "Long press",
  Skip: "Skip boot",
  Platform: "Game Management, Game Platform",
  helping: "We're already helping you sort out the local Game information",
  scan: "Local game scan",
  still: "If you still have a game platform that needs to be installed, You can choose more than one from the right, and we will help you download it",
  download: "Next and download the selected game platform",
  work: "Finishing the final work",
  Enjoy: "Enjoy your AYANEO",
  GoTo: "Go to the fun game!",
  complete: "complete",
  Start: "Start optimization",
  Guide: "Complete the Beginner Guide",
  toggle: "toggle",
  Selected: "Selected",
  many: "many",
  Press: "press",
  mark: "mark",
};
